services:
  # MySQL Database
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bookdb
      MYSQL_USER: bookuser
      MYSQL_PASSWORD: bookpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -prootpass" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s
    networks:
      - microservices-network

  # Pricing Service
  pricing-service:
    build:
      context: ./pricing-service
    container_name: pricing-service
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health/readiness" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # Book Service Instance 1
  book-service-1:
    build:
      context: ./book-service
    container_name: book-service-1
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - microservices-network

  # Book Service Instance 2
  book-service-2:
    build:
      context: ./book-service
    container_name: book-service-2
    ports:
      - "8083:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - microservices-network

  # Book Service Instance 3
  book-service-3:
    build:
      context: ./book-service
    container_name: book-service-3
    ports:
      - "8084:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - microservices-network

volumes:
  mysql_data:


networks:
  microservices-network:
    driver: bridge
