spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bookuser
    password: bookpass
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

# Pricing Service URL for Docker environment
pricing:
  service:
    url: http://pricing-service:8082
